### ISSUE TITLE
Always show code blocks in-line in the content

### ISSUE THREAD

**Issue by alexronquillo** [newrelic/developer-website#856]
### Is your feature request related to a problem? Please describe

When users view the developer site in a larger browser window, the code blocks render to the right of the text, instead of within the text, like when the viewport is smaller. This can cause issues (See #854) and make it harder to follow along.

### Describe the solution you'd like

Instead of arranging the code blocks on the side in larger windows, I'd like to see the text arranged in context always.

### Describe why this important to you

Arranging the code blocks on the side has a few unintended consequences:

- The way the code blocks change positions is more error prone
- The code blocks actually get smaller, even though the viewport is bigger, which means the reader sometimes has to scroll horizontally to see all the code
- It's harder to tell which code blocks go with what text
- It's inconsistent when code blocks are rendered on the side and in the text, even in larger viewports
- If the text leads into code blocks with a colon, the content doesn't read well, because there are a lot of hanging sentences:

### Additional context

Arranged in the text:

<img width="799" alt="Screen Shot 2020-10-16 at 1 04 16 PM" src="https://user-images.githubusercontent.com/8672090/96289778-9ba86880-0fb3-11eb-9cf7-3e4af4c387df.png">

Arranged on the side:

<img width="1003" alt="Screen Shot 2020-10-16 at 1 04 06 PM" src="https://user-images.githubusercontent.com/8672090/96289749-8e8b7980-0fb3-11eb-86f8-3dcd2f48aaf4.png">

Inconsistent arrangement:

<img width="1001" alt="Screen Shot 2020-10-16 at 1 27 19 PM" src="https://user-images.githubusercontent.com/8672090/96289813-abc04800-0fb3-11eb-8e44-0a277aca5cd2.png">

**Comment by jerelmiller** [comment]
@alexronquillo Funny enough, I also addressed this a bit with my innovation week. Here is a link to a PR build:

https://pr-855.dlyi50rq9kt6c.amplifyapp.com/automate-workflows/automated-tagging

This may or may not address your issue, but I'd love some feedback there and see if this at least eases some of that pain.

**NOTE:** Looks like there are some minor bugs to address in the terminal output, so ignore that for now. This PR is still in draft state and has some minor polish to address before that is ready to ship.

**Comment by jerelmiller** [comment]
There are definitely some pros/cons to the 2-column layout. The 2-column layout does restrict some of the horizontal space, but at the same time freeing some vertical space. That can be really handy for guides like the [map pageviews by region](https://pr-855.dlyi50rq9kt6c.amplifyapp.com/build-apps/map-pageviews-by-region) where you've got several code steps in a row. I tried that particular guide in the format shown on smaller screens (the code block immediately following the content) and I did have to screen more between steps to understand what changed.

That may or may not be a good reason to keep it, but just something I noticed while noodling around with that this week.

Some alternatives to explore as well:
* Configurable steps to specify the format
  Some stuff might make more sense in the single column flow, so maybe it makes sense to allow that to be configured
* Widen the right column. Right now the columns have equal space (50%, 50%), so maybe adjust this ratio? (40%, 60%)

**Comment by paperclypse** [comment]
I'd like to +1 Alex's suggestion.

I think it really comes down to the code blocks being unmoored from the text content on the right. When there's more than one code block, it starts to become quite confusing. 

A probably more complicated solution would be to design the two column layout so that the code blocks lined up well with their associated text. This would also mean, I expect, adding more vertical white space to the page.

**Comment by jerelmiller** [comment]
@alexronquillo @paperclypse I'd love for you to take a look at this PR build to see if this addresses some of the concerns. Any feedback is appreciated here!

https://pr-855.dlyi50rq9kt6c.amplifyapp.com/automate-workflows/automated-tagging

That PR does address the alignment issues that currently exist between the code blocks and its content. I plan to get the final bits of that PR in place and hope to have that in production by the end of the week (🤞 )

**Comment by alexronquillo** [comment]
@jerelmiller Thank you for sharing this! Fixing the alignment is a huge step in the right direction! I've looked at this document and others and have some questions and feedback:

While the alignment is fixed, I'm still not 100% convinced of the need for the 2-column layout. I just find it less predictable and less readable. For example:

<img width="1006" alt="Screen Shot 2020-10-19 at 2 18 25 PM" src="https://user-images.githubusercontent.com/8672090/96495527-fb05b300-1215-11eb-9404-9929c389a0b9.png">

I think you can still make out what is happening here, but when it's a single-column layout, the order in which the reader reads the content is more predictable:

<img width="870" alt="Screen Shot 2020-10-19 at 2 19 43 PM" src="https://user-images.githubusercontent.com/8672090/96495754-4029e500-1216-11eb-9f2a-0cd18a3f8400.png">

Also, the vertical space that it gives us seems like it is often wasted:

<img width="752" alt="Screen Shot 2020-10-19 at 2 21 46 PM" src="https://user-images.githubusercontent.com/8672090/96495863-77989180-1216-11eb-846b-a42ac3791aa5.png">

I am interested in exploring the option you mentioned:

> Configurable steps to specify the format. Some stuff might make more sense in the single column flow, so maybe it makes sense to allow that to be configured.

But I'd recommend the format that the author specifies be set in stone and not variable depending on the viewport. 

---

I appreciate your engagement in these requests! I feel like wherever we end up, users are really going to benefit from the changes you're making!

**Comment by jerelmiller** [comment]
@djsauble I'd also be curious to get your thoughts on this as well. 

I tend to like the 2-column for super-wide screens, since there is the horizontal real-estate available, but you make a ton of really good points that are very compelling. 

--- 

FYI, this isn't documented yet, but you can fix the alignment issue with the callout by using a JSX fragment to group the text and the callout together. This should at least provide a stopgap for some of those interesting areas of content:

````md
<>

Replace `<ADD YOUR ACCOUNT ID>` with your account id:

<Important>

Your account ID is available in the CLI quick start (see **Before you begin**).

</Important>

</>

```jsx
this.accountId = <ADD YOUR ACCOUNT ID>;
```
````

This results in the following:

<img width="1043" alt="Screen Shot 2020-10-19 at 1 09 54 PM" src="https://user-images.githubusercontent.com/565661/96506775-102a1400-120d-11eb-9441-8ea42d739de4.png">

**Comment by djsauble** [comment]
The two-column layout was my idea, so I take all the blame. 😄

I have a few thoughts about the issues raised here. The effectiveness of the design is inextricably linked to how the guides are written (and vice-versa). In cases where a two-column layout feels awkward, one solution could be to switch to a one-column layout, but an equally valid approach could be to rethink how the guides are written.

For example:

![image](https://user-images.githubusercontent.com/186715/96509362-bd525b80-1210-11eb-88e6-2bcc5e85dcdb.png)

This step should probably be split into two (as implied by the "First" and "Second" language here). Then, there's only one code block per step and no confusion about which text pertains to which code block.

<hr/>

Another example:

![image](https://user-images.githubusercontent.com/186715/96509463-e96ddc80-1210-11eb-8f8a-9de61cddfb8e.png)

Here, the misalignment could be solved by combining the command and the output into a single code block. In Jerel's innovation week demo, he showed how commands and output can be combined whilst ensuring that copy/paste applies only to the command which is the desired behavior here.

<hr/>

A final example:

![image](https://user-images.githubusercontent.com/8672090/96495863-77989180-1216-11eb-846b-a42ac3791aa5.png)

The point about excess vertical space is an excellent one. It feels wasteful, but at the same time, in a one-column design, the text would be visually out-weighed by the code block and not as easy to spot. Perhaps we could split the code blocks into separate steps, vertically center the text, and maybe reduce the max-height of the code blocks.

<hr/>

As a final thought, I've had a hypothesis that the two-column layout enables a sort of "expert mode" for people who are just looking for an overview of the steps or to get at the code as quickly as possible. By splitting the text and code into separate columns, it's much easier to _just_ scan the text and decide if it's worth my time to read the code as well, or to _just_ scan the code to figure out what I'm missing from my own code (e.g. maybe I'm getting stuck on a step and want to see if I'm missing any code blocks). If we force people to digest the guide via a single column, it becomes harder to pick the level of granularity you want.

**Comment by jerelmiller** [comment]
Thats a really good point on updating the guides. That last screenshot there is a great example. Its written the way it is because we didn't have a great ability to show the changes in the context of the entire file. There is no reason those 3 code blocks couldn't be combined into a single one with an updated description.

**Comment by alexronquillo** [comment]
@jerelmiller @djsauble I think you both raise really good points. I also agree that there are benefits of the two-column approach. I think, for me, the concern is more about how it changes from single-column to multi-column depending on the size of the view. I definitely agree that, given a two-column approach always, we could cater to the design by writing content differently. But, if there's a case where the optimally crafted text is different between the single-column and multi-column approaches, that's where things get a little messier. I looked at Apple's Swift UI tutorials, which have come up in various conversations, and it looks like they also move to a single-column approach in smaller viewports, but they also re-orient their experience (code blocks and images) to optimize for that single-column layout.

I 100% agree that, in the second example, the code and output should be combined and I've now seen the presentation from innovation week and am very excited about the ability to do this. In the final example, I agree with you as well. I would actually prefer to see more explanatory text, which would help fill some of that vertical space.

I'm glad you brought up the hypothesis about why the two column layout might be better. I wonder if part of the "I want only code ASAP" problem could be solved with Jerel's file-level code blocks (another great idea), regardless of if the alignment was one-column or two. So, an expert level user might be able to just zoom through the content to the end and copy the entire file, since the code would no longer be split up into separate chunks throughout the piece.

**Comment by alexronquillo** [comment]
@jpvajda could we revisit this?

I find myself using the:

```
<>

codeblock

</>
```

hack more and more to avoid awkard amounts of whitespace. We get a lot of these:

<img width="870" alt="Screen Shot 2022-02-09 at 10 28 14 AM" src="https://user-images.githubusercontent.com/8672090/153233749-f3ea1d27-f385-450f-a6ca-29c23f77b164.png">

**Comment by jpvajda** [comment]
@roadlittledawn for visibility. 👋

**Comment by kisielewskik** [comment]
@alexronquillo @jpvajda I made PR for that problem,
https://github.com/newrelic/developer-website/pull/2102
pleas review it if you will find some time :)

**Comment by jpvajda** [comment]
@kisielewskik Thanks for this contribution! I'll bring it to our engineering team's attention that this needs a quick review and merge into develop. cc @roadlittledawn / @zstix
